version: '3'
services:

    # PHP Service
    pro-app:
        build: ./
        image: pro/php
        container_name: pro-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            PHP_IDE_CONFIGS: serverName=Docker
        working_dir: /var/www/default
        volumes:
            - ./:/var/www/default
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./docker/supervisor/:/etc/supervisor/
        networks:
            - pro-app-network
        extra_hosts:
            - host.docker.internal:host-gateway


    # Postgresql Service
    pro-db:
        image: postgres:17.1
        container_name: pro-db
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_EXTERNAL_PORT}:5432"
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./docker/db-dump:/db-dump
        networks:
            - pro-app-network

    # Nginx Service
    pro-webserver:
        image: nginx:alpine
        container_name: pro-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_EXTERNAL_PORT}:80"
            - "443:443"
            - "5173:5173"
        volumes:
            - ./:/var/www/default
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx
            - /var/www/assets:/var/www/assets
        networks:
            - pro-app-network
        depends_on:
            - pro-app
            - pro-db

# Docker Networks
networks:
    pro-app-network:
        driver: bridge

# Volumes
volumes:
    pgdata:
        driver: local
